### ISSUE TITLE
Pubky Backend Development Roadmap

### ISSUE THREAD

**Issue by SHAcollision** [pubky/pubky-nexus#1]
This issue is intended to hold the overarching planning for the Pubky-app backend rewrite (old `skunk-work` indexer).

The `pubky-app-backend` job is to listen to raw Homeserver event streams and craft a fast access indexed view akin to social media that can be directly consumed by the [pubky-app](https://github.com/pubky/pubky-app) client and other apps.

## The tech stack
- Framework: [Axum](https://github.com/tokio-rs/axum)
- Social DB: [Neo4J](https://github.com/neo4j/neo4j) 
- Fast DB: [Redis](https://github.com/redis/redis) (alternatively we can use LMDB)

**Context on tech stack selection** : https://docs.google.com/presentation/u/1/d/1iBZHc-n5zA4teLLdpxuUy7lQUyV3ftuxUDTUUxbajCM/edit#slide=id.g2eb1d44cdab_0_1

## Objective for Alpha v0.1.0 Milestone
Reach feature parity with `skunk-work` improving on the following:
1. High performance: no inneficient lookups, rust performance, modern stack.
2. Clear vision forward: easy implementation of exciting features: WoT, graph queries, etc.
3. Free of bugs: hopefully.
4. Cleaner dev experience.

## Architecture
![image](https://github.com/user-attachments/assets/e516ceff-d28f-4d71-9123-96eb1725cd73)

1. The watcher does effectively work as an aggregator/translator.
2. The service reads from indexes or queries the graph and serves the pubky-app clients.
5. The social graph DB (Neo4J) is intended for holding a complete view of the network. It should be queried as little as possible but we can abuse it at the beginning in order to complete features faster.
6. As long as it is possible and not too troublesome, most relationships, query results and cache should be indexed by `key: value` and retrieved from Redis. We should take inspiration on current use of LMDB in `skunk-works`.

### 1. Architecture
- [x] #2
- [x] #3
- [x] Create empty REST API server "main.rs"
- [x] Create empty listener service for Homserver stream of events "watcher.rs"
- [x] Create / write connectors for Neo4J 
- [x] Create / write connectors for Redis
- [ ] Optionally implement some tooling: e.g., [benchmarking](https://github.com/bheisler/criterion.rs) for regression testing or much later on fuzzy tests to early catch bugs/exploits.

## 2. REST service `main.rs`
- [ ] Implement dummy endpoints for all existing `skunk-work` indexer routes. For example `/alpha-v0.1.0/pubky.app/profile/:userId` .
- [x] We can temporarily develop using as placeholder for Neo4J DB the `/neo4j-example/indexer-migration.cypher` created with the `skunk-work/scripts/genCypher.js` https://github.com/pubky/skunk-works/pull/120 on July 6th.
- [x] Establish graph models, so far this seems to be useful:
![schema](https://github.com/pubky/pubky-nexus/raw/main/docs/images/pubky-nexus-graph.png)
    - Nodes:
      - Users
      - Posts
    - Relationships:
      - Follows (User to User)
      - Authored (User to Post)
      - Tagged (User to Post/User)
      - Replied (Post to Post)
      - Reposted (Post to Post)
      - Mentioned (Post to User)
      - Bookmarked (User to Post)
- [x] Establish key-value schemas. We can take inspiration and use as base the current LMDB schemas from `skunk-works`.
- [ ] One by one start completing the logic and utils needed to serve real requests on our dummy endpoints from our DBs. #27 

## 3. Homeserver subscriber `watcher.rs` .
- [ ] If `pubky/pubky` [homeserver event streaming](https://github.com/pubky/pubky/pull/5) is not ready we can create a mockup stream of events (postman).
- [ ] Implement `on_new_event...` handlers. Each event should be handled and new entries should be entered (nodes/relationships) into our graph DB and new indexes and notifications into our key-value DB.

## 4. Pubky-app SDK
- [ ] Strongly consider ditching the concept of an "SDK" (like the existing JS SDK) in favour of an Open API specification that the client can conform to. Challenge: pk-user creation and auth.
- [ ] New SDK must more explicitly differentiate between homeserver and indexer requests and their uses.
- [ ] Extract `packages/sdk` from `skunk-works` into it's own `pubky-app-sdk` repository.
- [ ] Update `sdk` to work well with the new routes and schema `/alpha-v0.1.0/pubky.app/...`

#### Selfhosting
- [ ]  Add optionality to only index low resource intensive views (only key-value) and only a subset of users/homeservers based. This would allow anyone to craft their own view of the social network at home with machines like Umbrel / StartOS. 
- [ ]  If a user's `pubky-app-backend` cannot serve some specific request, the client app could ask the user permission to query the more powerful/featurerich Synonym `pubky-app-backend`
#### WoT 
...

**Comment by SHAcollision** [comment]
We are done with feature parity. Closing.
